server:
  port: 8001
  
spring:
  data:
    mongodb:
      database: student
      host: localhost
  application:
    name: STUDENT-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
